image: kaiwinter/docker-java8-maven

stages:
  - build
  - test
  - report
  - deploy

maven_jar:
  stage: build
  script:
    - echo "[+] Building Project Jar With Maven"
    - cd Notes
    - mvn jfx:jar
    - echo "[-] Building Jar Done"

maven_native:
  stage: build
  script:
    - echo "[+] Building Project Native With Maven"
    - cd Notes
    - mvn jfx:native
    - echo "[-] Building Native Done"

maven_test:
  stage: test
  script:
    - echo "[+] Testing Project"
    - cd Notes
    - mvn test
    - echo "[-] Finished Testing"

sloc_report:
  stage: report
  script:
    - npm install sloc
    - cd ./scripts
    - mkdir -p loc
    - echo ./loc.sh > ./loc/report.txt
  artifacts:
    paths:
      - loc/

pages:
  stage: deploy
  dependencies:
    - sloc_report
  script:
    - mv loc/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master


