image: kaiwinter/docker-java8-maven

stages:
  - build
  - test
  - deploy

maven_jar:
  stage: build
  script:
    - echo "[+] Building Project Jar With Maven"
    - cd Notes
    - mvn jfx:jar
    - echo "[-] Building Jar Done"

maven_native:
  stage: build
  script:
    - echo "[+] Building Project Native With Maven"
    - cd Notes
    - mvn jfx:native
    - echo "[-] Building Native Done"

maven_test:
  stage: test
  script:
    - echo "[+] Testing Project"
    - cd Notes
    - mvn test
    - echo "[-] Finished Testing"

sloc_build:
  image: node:4.2.2
  stage: build
  script:
    - cd ./scripts
    - npm install
    - mkdir -p loc
    - ./loc.sh > ./loc/report.txt
  artifacts:
    paths:
      - scripts/loc/

pages:
  stage: deploy
  dependencies:
    - sloc_build
  script:
    - mkdir -p public/loc/
    - mv scripts/loc/ public/loc/
  artifacts:
    paths:
      - public
    expire_in: 14 days
  only:
    - master


